apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: us-docker.pkg.dev/level-agent-460100-t6/philopater-repository/simple-python-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENVIRONMENT
          value: "DEV"
        - name: HOST
          value: "localhost"
        - name: PORT
          value: "8000"
        - name: REDIS_HOST
          value: "redis"          
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"